//===- Lexer.h - Lexer for the Toy language -------------------------------===//
//
// This file implements a simple Lexer for the Toy language.
//
//===----------------------------------------------------------------------===//

#ifndef TOY_LEXER_H
#define TOY_LEXER_H

#include "llvm/ADT/StringRef.h"

#include <cassert>
#include <cctype>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <memory>
#include <string>

namespace toy {

/// Defines the location in a file
struct SourceLocation {
  std::shared_ptr<std::string> File; ///< filename.
  int Line;                          ///< line number.
  int Col;                           ///< column number.
};

/// List of tokens generated by the Lexer
enum class Token : int8_t {
  Semicolon = ';',
  Colon = ',',
  ParenthesesOpen = '(',
  ParenthesesClose = ')',
  BracketOpen = '{',
  BracketClose = '}',
  SbracketOpen = '[',
  SbracketClose = ']',
  Plus = '+',
  Minus = '-',
  Asterisk = '*',
  Slash = '/',
  Less = '<',
  Greater = '>',
  Equal = '=',
  // Special
  Eof = -1,
  Space = -2,
  // Commands
  Return = -3,
  Var = -4,
  Def = -5,
  Print = -6,
  Transpose = -7,
  // Primary
  Identifier = -8,
  Number = -9,
  // Unknown
  Unknown = -99,
};

/// Convert a reserved word to a Token
inline Token wordToToken(std::string Word) {
  if (Word == "return")
    return Token::Return;

  if (Word == "def")
    return Token::Def;

  if (Word == "var")
    return Token::Var;

  if (Word == "print")
    return Token::Print;
  
  if (Word == "transpose")
    return Token::Transpose;

  return Token::Identifier;
}

inline llvm::StringRef tokenToWord(Token Tok) {
  switch (Tok) {
  case Token::Semicolon:
    return "SEMICOLON";
  case Token::Colon:
    return "COLON";
  case Token::ParenthesesOpen:
    return "PARENTHESE_OPEN";
  case Token::ParenthesesClose:
    return "PARENTHESES_CLOSE";
  case Token::BracketOpen:
    return "BRACKET_OPEN";
  case Token::BracketClose:
    return "BRACKET_CLOSE";
  case Token::SbracketOpen:
    return "SBRACKET_OPEN";
  case Token::SbracketClose:
    return "SBRACKET_CLOSE";
  case Token::Plus:
    return "PLUS";
  case Token::Minus:
    return "MINUS";
  case Token::Asterisk:
    return "ASTERISK";
  case Token::Slash:
    return "SLASH";
  case Token::Less:
    return "LESS";
  case Token::Greater:
    return "GREATER";
  case Token::Equal:
    return "EQUAL";
  case Token::Eof:
    return "EOF";
  case Token::Space:
    return "SPACE";
  case Token::Return:
    return "RETURN";
  case Token::Var:
    return "VAR";
  case Token::Def:
    return "DEF";
  case Token::Print:
    return "PRINT";
  case Token::Transpose:
    return "TRANSPOSE";
  case Token::Identifier:
    return "IDENTIFIER";
  case Token::Number:
    return "NUMBER";
  default:
    return "UNKNOWN";
  }
}

/// Convert char to Token
inline Token charToToken(char C) {
  switch (C) {
  case ';':
    return Token::Semicolon;
  case ',':
    return Token::Colon;
  case '(':
    return Token::ParenthesesOpen;
  case ')':
    return Token::ParenthesesClose;
  case '{':
    return Token::BracketOpen;
  case '}':
    return Token::BracketClose;
  case '[':
    return Token::SbracketOpen;
  case ']':
    return Token::SbracketClose;
  case '+':
    return Token::Plus;
  case '-':
    return Token::Minus;
  case '*':
    return Token::Asterisk;
  case '/':
    return Token::Slash;
  case '<':
    return Token::Less;
  case '>':
    return Token::Greater;
  case '=':
    return Token::Equal;
  default:
    return Token::Unknown;
  }
}

/// The Lexer is an abstract base class providing all the facilities that the
/// Parser expects. It goes through the stream one token at a time and keeps
/// track of the location in the file for debugging purpose. It relies on a
/// subclass to provide a `readNextLine()` method. The subclass can proceed by
/// reading the next line from the standard input or from a memory mapped file.
class Lexer {
public:
  /// Create a lexer for the given filename. The filename is kept only for
  /// debugging purpose.
  Lexer(std::string Filename)
      : LastLocation(
            {std::make_shared<std::string>(std::move(Filename)), 0, 0}) {}

  virtual ~Lexer() = default;

  /// Look at the current token in the stream.
  Token getCurToken() { return CurTok; }

  /// Get next token in the stream and return it.
  Token getNextToken() { return CurTok = getTok(); }

  /// Move to the next token in the stream, asserting on the current token
  /// matching the expectation.
  void consume([[maybe_unused]] Token Tok) {
    assert(Tok == CurTok && "Consume token mismatch expectation.");
    getNextToken();
  }

  /// Return the current identifier (prereq: getCurToken() == Token::Identifier)
  llvm::StringRef getId() {
    assert(CurTok == Token::Identifier && "Current token is not a identifier.");
    return IdentifierStr;
  }

  /// Return the current number (prereq: getCurToken() == Token::Number)
  double getNumber() {
    assert(CurTok == Token::Number && "Current token is not a number.");
    return NumVal;
  }

  /// Return the Location for the beginning of the current token.
  SourceLocation getLastLocation() { return LastLocation; }

  /// Return the current line in the file.
  int getLine() { return LastLocation.Line; }

  /// Return the column in the file.
  int getOl() { return LastLocation.Col; }

private:
  /// The last token read from the input.
  Token CurTok = Token::Eof;

  /// Localtion for `CurTok`
  SourceLocation LastLocation;

  /// If the current Token is a identifier, this string contains  the value.
  std::string IdentifierStr;

  /// If the current token is a number, this contains the value
  double NumVal = 0.0;

  /// The last value returned by getNextChar(). We need to keep it around as we
  /// always need to read ahead one character to decide when to end a token and
  /// we can't put it back in the stream after reading from it.
  int LastChar = ' ';

  /// Keep track of the current line number in the input stream
  int CurLineNum = 0;

  /// Keep track of the current column number in the input stream
  int CurColNum = 0;

  /// Buffer supplied by the derived class on calls to `readNextLine()`
  llvm::StringRef CurLineBuffer = "\n";

  /// Delegate to a derived class fetching the next line. Returns an empty
  /// string to a signal end of file (EOF). Liners are expected to always finish
  /// with "\n".
  virtual llvm::StringRef readNextLine() = 0;

  /// Return the next character from the stream. This manages the buffer for the
  /// current line and request the next line buffer to the derived class as
  /// needed.
  int getNextChar() {
    // The current line buffer should not be empty unless it is the end of file.
    if (CurLineBuffer.empty()) {
      return EOF;
    }

    CurColNum++;

    auto NextChar = CurLineBuffer.front();
    CurLineBuffer = CurLineBuffer.drop_front();

    if (CurLineBuffer.empty()) {
      CurLineBuffer = readNextLine();
    }

    if (NextChar == '\n') {
      CurLineNum++;
      CurColNum = 0;
    }

    return NextChar;
  }

  /// Return the next token from standard input.
  Token getTok() {
    // Skip any whitespace
    while (isspace(LastChar)) {
      LastChar = getNextChar();
    }

    // Save the current location before reading the token characters.
    LastLocation.Line = CurLineNum;
    LastLocation.Col = CurColNum;

    // Identifier: [a-zA-Z][a-zA-Z0-9_]*
    if (isalpha(LastChar)) {
      IdentifierStr = static_cast<char>(LastChar);
      while (isalnum(LastChar = getNextChar()) || LastChar == '_') {
        IdentifierStr += static_cast<char>(LastChar);
      }

      return wordToToken(IdentifierStr);
    }

    // Number: [0-9.]+
    if (isdigit(LastChar) || LastChar == '.') {
      std::string NumStr;

      do {
        NumStr += static_cast<char>(LastChar);
        LastChar = getNextChar();
      } while (isdigit(LastChar) || LastChar == '.');

      NumVal = strtod(NumStr.c_str(), nullptr);
      return Token::Number;
    }

    if (LastChar == '#') {
      // Comment until end of line
      do {
        LastChar = getNextChar();
      } while (LastChar != EOF && LastChar != '\n' && LastChar != '\r');

      if (LastChar != EOF) {
        return getTok();
      }
    }

    // Check for end of file. Don't eat the EOF
    if (LastChar == EOF) {
      return Token::Eof;
    }

    // Otherwise just return the token.
    Token Tok = charToToken(static_cast<char>(LastChar));
    LastChar = getNextChar();
    return Tok;
  }
};

/// Lexer implementation to operate on a memory buffer
class LexerBuffer final : public Lexer {
public:
  LexerBuffer(const char *Begin, const char *End, std::string Filename)
      : Lexer(std::move(Filename)), Current(Begin), EndOfBuffer(End) {}

private:
  const char *Current, *EndOfBuffer;

  llvm::StringRef readNextLine() override {
    auto *Begin = Current;
    while (Current <= EndOfBuffer && *Current && *Current != '\n') {
      Current++;
    }

    if (Current <= EndOfBuffer && *Current) {
      Current++;
    }

    llvm::StringRef Result{Begin, static_cast<size_t>(Current - Begin)};
    return Result;
  }
};

} // namespace toy

#endif // TOY_LEXER_H
