//===- Lexer.h - Lexer for the Toy language -------------------------------===//
//
// Part of the MLIR Toy project, under the Apache License v2.0 with LLVM
// Exceptions. See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// Modified by: Victor Briganti in 2026
//
//===----------------------------------------------------------------------===//
// This file implements a simple Lexer for the Toy language.
//
//===----------------------------------------------------------------------===//

#ifndef TOY_LEXER_H
#define TOY_LEXER_H

#include <cassert>
#include <cctype>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <memory>
#include <string>

#include "llvm/ADT/StringRef.h"

namespace toy {

/// Defines the location in a file
struct SourceLocation {
  std::shared_ptr<std::string> file; ///< filename.
  int line;                          ///< line number.
  int col;                           ///< column number.
};

/// List of tokens generated by the Lexer
enum class Token : int8_t {
  Semicolon = ';',
  Comma = ',',
  ParenthesesOpen = '(',
  ParenthesesClose = ')',
  BraceOpen = '{',
  BraceClose = '}',
  BracketOpen = '[',
  BracketClose = ']',
  Plus = '+',
  Minus = '-',
  Asterisk = '*',
  Slash = '/',
  Less = '<',
  Greater = '>',
  Equal = '=',
  // Special
  Eof = -1,
  Space = -2,
  // Commands
  Return = -3,
  Var = -4,
  Def = -5,
  // Primary
  Identifier = -6,
  Number = -7,
  // Unknown
  Unknown = -99,
};

/// Convert a reserved word to a Token
inline Token wordToToken(const std::string &word) {
  if (word == "return")
    return Token::Return;

  if (word == "def")
    return Token::Def;

  if (word == "var")
    return Token::Var;

  return Token::Identifier;
}

inline llvm::StringRef tokenToWord(const Token &tok) {
  switch (tok) {
  case Token::Semicolon:
    return "SEMICOLON";
  case Token::Comma:
    return "COMMA";
  case Token::ParenthesesOpen:
    return "PARENTHESE_OPEN";
  case Token::ParenthesesClose:
    return "PARENTHESES_CLOSE";
  case Token::BraceOpen:
    return "BRACE_OPEN";
  case Token::BraceClose:
    return "BRACE_CLOSE";
  case Token::BracketOpen:
    return "BRACKET_OPEN";
  case Token::BracketClose:
    return "BRACKET_CLOSE";
  case Token::Plus:
    return "PLUS";
  case Token::Minus:
    return "MINUS";
  case Token::Asterisk:
    return "ASTERISK";
  case Token::Slash:
    return "SLASH";
  case Token::Less:
    return "LESS";
  case Token::Greater:
    return "GREATER";
  case Token::Equal:
    return "EQUAL";
  case Token::Eof:
    return "EOF";
  case Token::Space:
    return "SPACE";
  case Token::Return:
    return "RETURN";
  case Token::Var:
    return "VAR";
  case Token::Def:
    return "DEF";
  case Token::Identifier:
    return "IDENTIFIER";
  case Token::Number:
    return "NUMBER";
  default:
    return "UNKNOWN";
  }
}

/// Convert char to Token
inline Token charToToken(const char &C) {
  switch (C) {
  case ';':
    return Token::Semicolon;
  case ',':
    return Token::Comma;
  case '(':
    return Token::ParenthesesOpen;
  case ')':
    return Token::ParenthesesClose;
  case '{':
    return Token::BraceOpen;
  case '}':
    return Token::BraceClose;
  case '[':
    return Token::BracketOpen;
  case ']':
    return Token::BracketClose;
  case '+':
    return Token::Plus;
  case '-':
    return Token::Minus;
  case '*':
    return Token::Asterisk;
  case '/':
    return Token::Slash;
  case '<':
    return Token::Less;
  case '>':
    return Token::Greater;
  case '=':
    return Token::Equal;
  default:
    return Token::Unknown;
  }
}

/// Convert Token to char
inline char tokenToChar(const Token &tok) {
  switch (tok) {
  case Token::Plus:
    return '+';
  case Token::Minus:
    return '-';
  case Token::Asterisk:
    return '*';
  case Token::Slash:
    return '/';
  case Token::Less:
    return '<';
  case Token::Greater:
    return '>';
  case Token::Equal:
    return '=';
  default:
    return '\0';
  }
}

/// The Lexer is an abstract base class providing all the facilities that the
/// Parser expects. It goes through the stream one token at a time and keeps
/// track of the location in the file for debugging purpose. It relies on a
/// subclass to provide a `readNextLine()` method. The subclass can proceed by
/// reading the next line from the standard input or from a memory mapped file.
class Lexer {
public:
  /// Create a lexer for the given filename. The filename is kept only for
  /// debugging purpose.
  Lexer(std::string filename)
      : lastLocation(
            {std::make_shared<std::string>(std::move(filename)), 0, 0}) {}

  virtual ~Lexer() = default;

  /// Look at the current token in the stream.
  Token getCurToken() { return curTok; }

  /// Get next token in the stream and return it.
  Token getNextToken() { return curTok = getTok(); }

  /// Move to the next token in the stream, asserting on the current token
  /// matching the expectation.
  void consume([[maybe_unused]] Token tok) {
    assert(tok == curTok && "Consume token mismatch expectation.");
    getNextToken();
  }

  /// Return the current identifier (prereq: getCurToken() == Token::Identifier)
  llvm::StringRef getId() {
    assert(curTok == Token::Identifier && "Current token is not a identifier.");
    return identifierStr;
  }

  /// Return the current number (prereq: getCurToken() == Token::Number)
  double getNumber() {
    assert(curTok == Token::Number && "Current token is not a number.");
    return numVal;
  }

  /// Return the Location for the beginning of the current token.
  SourceLocation getLastLocation() { return lastLocation; }

  /// Return the current line in the file.
  int getLine() { return lastLocation.line; }

  /// Return the column in the file.
  int getOl() { return lastLocation.col; }

private:
  /// The last token read from the input.
  Token curTok = Token::Eof;

  /// Localtion for `CurTok`
  SourceLocation lastLocation;

  /// If the current Token is a identifier, this string contains  the value.
  std::string identifierStr;

  /// If the current token is a number, this contains the value
  double numVal = 0.0;

  /// The last value returned by getNextChar(). We need to keep it around as we
  /// always need to read ahead one character to decide when to end a token and
  /// we can't put it back in the stream after reading from it.
  int lastChar = ' ';

  /// Keep track of the current line number in the input stream
  int curLineNum = 0;

  /// Keep track of the current column number in the input stream
  int curColNum = 0;

  /// Buffer supplied by the derived class on calls to `readNextLine()`
  llvm::StringRef curLineBuffer = "\n";

  /// Delegate to a derived class fetching the next line. Returns an empty
  /// string to a signal end of file (EOF). Liners are expected to always finish
  /// with "\n".
  virtual llvm::StringRef readNextLine() = 0;

  /// Return the next character from the stream. This manages the buffer for the
  /// current line and request the next line buffer to the derived class as
  /// needed.
  int getNextChar() {
    // The current line buffer should not be empty unless it is the end of file.
    if (curLineBuffer.empty()) {
      return EOF;
    }

    curColNum++;

    auto nextChar = curLineBuffer.front();
    curLineBuffer = curLineBuffer.drop_front();

    if (curLineBuffer.empty()) {
      curLineBuffer = readNextLine();
    }

    if (nextChar == '\n') {
      curLineNum++;
      curColNum = 0;
    }

    return nextChar;
  }

  /// Return the next token from standard input.
  Token getTok() {
    // Skip any whitespace
    while (isspace(lastChar)) {
      lastChar = getNextChar();
    }

    // Save the current location before reading the token characters.
    lastLocation.line = curLineNum;
    lastLocation.col = curColNum;

    // Identifier: [a-zA-Z][a-zA-Z0-9_]*
    if (isalpha(lastChar)) {
      identifierStr = static_cast<char>(lastChar);
      while (isalnum(lastChar = getNextChar()) || lastChar == '_') {
        identifierStr += static_cast<char>(lastChar);
      }

      return wordToToken(identifierStr);
    }

    // Number: [0-9.]+
    if (isdigit(lastChar) || lastChar == '.') {
      std::string NumStr;

      do {
        NumStr += static_cast<char>(lastChar);
        lastChar = getNextChar();
      } while (isdigit(lastChar) || lastChar == '.');

      numVal = strtod(NumStr.c_str(), nullptr);
      return Token::Number;
    }

    if (lastChar == '#') {
      // Comment until end of line
      do {
        lastChar = getNextChar();
      } while (lastChar != EOF && lastChar != '\n' && lastChar != '\r');

      if (lastChar != EOF) {
        return getTok();
      }
    }

    // Check for end of file. Don't eat the EOF
    if (lastChar == EOF) {
      return Token::Eof;
    }

    // Otherwise just return the token.
    Token Tok = charToToken(static_cast<char>(lastChar));
    lastChar = getNextChar();
    return Tok;
  }
};

/// Lexer implementation to operate on a memory buffer
class LexerBuffer final : public Lexer {
public:
  LexerBuffer(const char *begin, const char *end, std::string filename)
      : Lexer(std::move(filename)), current(begin), endOfBuffer(end) {}

private:
  const char *current, *endOfBuffer;

  llvm::StringRef readNextLine() override {
    auto *begin = current;
    while (current <= endOfBuffer && *current && *current != '\n') {
      current++;
    }

    if (current <= endOfBuffer && *current) {
      current++;
    }

    llvm::StringRef result{begin, static_cast<size_t>(current - begin)};
    return result;
  }
};

} // namespace toy

#endif // TOY_LEXER_H
